version: "3"
services:
  db:
    image: "postgres:12-alpine"
    env_file: .env.local
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  attribution-generator-api:
    build: "https://github.com/konekto/attribution-generator-api.git"
    ports:
      - "8181:8181"

volumes:
  database:
    driver: local
